In [1]:
pip install deep_translator

Collecting deep_translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Collecting beautifulsoup4<5.0.0,>=4.9.1 (from deep_translator)
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ---------------------------------------- 0.0/143.0 kB ? eta -:--:--
     ------- ----------------------------- 30.7/143.0 kB 660.6 kB/s eta 0:00:01
     ----------------------------------- -- 133.1/143.0 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 143.0/143.0 kB 1.2 MB/s eta 0:00:00
Collecting requests<3.0.0,>=2.23.0 (from deep_translator)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting soupsieve>1.2 (from beautifulsoup4<5.0.0,>=4.9.1->deep_translator)
  Downloading soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting charset-normalizer<4,>=2 (from requests<3.0.0,>=2.23.0->deep_translator)
  Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests<3.0.0,>=2.23.0->deep_translator)
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ---------------------------------------- 0.0/61.5 kB ? eta -:--:--
     ---------------------------------------- 61.5/61.5 kB ? eta 0:00:00
Collecting urllib3<3,>=1.21.1 (from requests<3.0.0,>=2.23.0->deep_translator)
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests<3.0.0,>=2.23.0->deep_translator)
  Downloading certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ---------------------------------------- 0.0/42.3 kB ? eta -:--:--
   ---------------------------------------- 42.3/42.3 kB 2.0 MB/s eta 0:00:00
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 0.0/62.6 kB ? eta -:--:--
   ---------------------------------------- 62.6/62.6 kB ? eta 0:00:00
Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
   ---------------------------------------- 0.0/158.3 kB ? eta -:--:--
   ------------------------------------ --- 143.4/158.3 kB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 158.3/158.3 kB 3.2 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
   ---------------------------------------- 0.0/100.4 kB ? eta -:--:--
   -------------------------------- ------- 81.9/100.4 kB 2.2 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   ------------------------------------ --- 92.2/100.4 kB 1.3 MB/s eta 0:00:01
   -------------------------------------- 100.4/100.4 kB 250.4 kB/s eta 0:00:00
Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
   ---------------------------------------- 0.0/104.6 kB ? eta -:--:--
   ---------------------------------------  102.4/104.6 kB 2.9 MB/s eta 0:00:01
   ---------------------------------------- 104.6/104.6 kB 2.0 MB/s eta 0:00:00
Installing collected packages: urllib3, soupsieve, idna, charset-normalizer, certifi, requests, beautifulsoup4, deep_translator
Successfully installed beautifulsoup4-4.12.2 certifi-2023.7.22 charset-normalizer-3.3.2 deep_translator-1.11.4 idna-3.4 requests-2.31.0 soupsieve-2.5 urllib3-2.1.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('maribelajar-steming.csv')

df

     Unnamed: 0                     Steming
0             0                 terimakasih
1             1      nyimpan gamenya gimana
2             2                  save world
3             3                       bagus
4             4  subscribe boss terimakasih
..          ...                         ...
145         145       simak kemarin tinggal
146         146                       simak
147         147                         NaN
148         148                 terimakasih
149         149      password dimasukin gan

[150 rows x 2 columns]

In [4]:
df.drop(df.columns[[0]], axis = 1, inplace = True)
df

                        Steming
0                   terimakasih
1        nyimpan gamenya gimana
2                    save world
3                         bagus
4    subscribe boss terimakasih
..                          ...
145       simak kemarin tinggal
146                       simak
147                         NaN
148                 terimakasih
149      password dimasukin gan

[150 rows x 1 columns]

In [5]:
df.dropna()

                        Steming
0                   terimakasih
1        nyimpan gamenya gimana
2                    save world
3                         bagus
4    subscribe boss terimakasih
..                          ...
144           matur terimakasih
145       simak kemarin tinggal
146                       simak
148                 terimakasih
149      password dimasukin gan

[147 rows x 1 columns]

In [6]:
from deep_translator import GoogleTranslator

def Translate(text):
    text = GoogleTranslator(source='id', target='en').translate(text)
    return text

In [8]:
 print(df.isnull().sum())

Steming    3
dtype: int64

In [9]:
df.dropna(subset=["Steming"], axis=0, inplace=True)

In [10]:
 print(df.isnull().sum())

Steming    0
dtype: int64

In [11]:
df['Text_Inggris'] = df['Steming'].apply(Translate)

In [12]:
df

                        Steming               Text_Inggris
0                   terimakasih                  Thank You
1        nyimpan gamenya gimana  how do you save the game?
2                    save world                 save world
3                         bagus                       Good
4    subscribe boss terimakasih   subscribe boss thank you
..                          ...                        ...
144           matur terimakasih        thank you very much
145       simak kemarin tinggal       stay tuned yesterday
146                       simak                take a look
148                 terimakasih                  Thank You
149      password dimasukin gan    Enter the password, bro

[147 rows x 2 columns]

In [13]:
keep_col = ['Steming','Text_Inggris']
df1 = df[keep_col]
df1.to_csv('maribelajar-translate.csv')